DROP TABLE B1_BANK;
DROP TABLE B1_TRANSACTIONS;

CREATE TABLE B1_BANK
(
ACCOUNT_NUMBER NUMBER(10),
USER_NAME VARCHAR2(20),
PASSWORD VARCHAR2(20),
NAME VARCHAR2(20),
AMOUNT NUMBER(10),
EMAIL_ID VARCHAR2(20),
CREATION_DATE DATE
);

CREATE SEQUENCE ACCOUNT_NUMBER_SEQ
START WITH 201401 INCREMENT BY 1;

ALTER TABLE B1_BANK ADD
(
CONSTRAINT PK_ACCOUNT_NUMBER
PRIMARY KEY(ACCOUNT_NUMBER)
);

CREATE TABLE B1_TRANSACTIONS
(
TRANS_ID NUMBER(10),
ACCOUNT_NUMBER NUMBER(10),
TRANSACTION VARCHAR2(20), 
TRANSACTION_DATE DATE,
AMOUNT NUMBER(10),
DESCRIPTION VARCHAR2(10) 
);

ALTER TABLE B1_TRANSACTIONS ADD
(
CONSTRAINT FK_ACCOUNT_NUMBER
FOREIGN KEY(ACCOUNT_NUMBER)
REFERENCES B1_BANK(ACCOUNT_NUMBER)
ON DELETE CASCADE 
);
